[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ivi-lightmatter"
version = "0.1.0"
description = "Adapters that connect Lightmatter time-thickness physics to IVI."
authors = [{ name = "Kantian-IVI Project" }]
requires-python = ">=3.10"
dependencies = ["ivi-core>=0.1.0", "numpy>=1.24"]

[project.optional-dependencies]
dev = ["pytest>=7"]

[tool.setuptools.packages.find]
where = ["."]
include = ["ivi_lightmatter*"]
