[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ivi-core"
version = "0.1.0"
description = "Kantian IVI abstractions for resuperposition/i-projection interfaces."
authors = [{ name = "Kantian-IVI Project" }]
requires-python = ">=3.10"
dependencies = ["numpy>=1.24"]

[project.optional-dependencies]
dev = ["pytest>=7"]

[tool.setuptools.packages.find]
where = ["."]
include = ["ivi_core*"]
